version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_database
    networks:
      - fastapi_network

  app:
    container_name: app
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - fastapi_network
    restart: always

networks:
  fastapi_network:
    